flags: {}
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- .
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/ast
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/backend-ghc
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/rewrite
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/prettyprint
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/refactor
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/builtin-refactorings
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/experimental-refactorings
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/demo
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/cli
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/debug
- /home/anabra/ELTE/Haskell_Tools/ht-repo/haskell-tools/src/daemon
extra-deps:
- fswatch-0.1.0.1
- haskell-tools-ast-0.9.0.0
- haskell-tools-backend-ghc-0.9.0.0
- haskell-tools-cli-0.9.0.0
- haskell-tools-daemon-0.9.0.0
- haskell-tools-debug-0.9.0.0
- haskell-tools-demo-0.9.0.0
- haskell-tools-prettyprint-0.9.0.0
- haskell-tools-refactor-0.9.0.0
- haskell-tools-rewrite-0.9.0.0
- incremental-sat-solver-0.1.8
resolver: lts-9.3
